interpreter = ["bash", "-euo", "pipefail", "-c"]

[task.create-foo]
script = "touch foo"

[task.create-bar]
script = "touch bar"

[task.stat-both]
script = "stat foo bar"
depends = ["create-foo", "create-bar"]

[task.delete-foo]
script = "rm foo"
depends = ["create-foo", "stat-both"]

[task.delete-bar]
script = "rm bar"
depends = ["create-bar", "stat-both"]
