interpreter = ["bash", "-euo", "pipefail", "-c"]

[tasks.create-foo]
script = "touch foo"

[tasks.create-bar]
script = "touch bar"

[tasks.stat-both]
script = "stat foo bar"
depends = ["create-foo", "create-bar"]

[tasks.delete-foo]
script = "rm foo"
depends = ["create-foo", "stat-both"]

[tasks.delete-bar]
script = "rm bar"
depends = ["create-bar", "stat-both"]
