[processes.create-foo]
command = ["touch", "foo"]

[processes.create-bar]
command = ["touch", "bar"]

[processes.delete-foo]
command = ["rm", "foo"]
after = ["create-foo"]

[processes.delete-bar]
command = ["rm", "bar"]
after = ["create-bar"]

[processes.stat-both]
command = ["stat", "foo", "bar"]
after = ["create-foo", "create-bar"]
before = ["delete-foo", "delete-bar"]
