stages:
  - ci
  - deploy

variables:
  # Makes some things print in color.
  TERM: ansi

before_script:
  # Enable nix-command and flakes.
  - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

  # Add nix-community binary cache.
  - echo "extra-substituters = https://nix-community.cachix.org" >> /etc/nix/nix.conf
  - echo "extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" >> /etc/nix/nix.conf

  # Install direnv and nix-direnv.
  - nix profile install --impure --inputs-from ./nix nixpkgs#direnv nixpkgs#nix-direnv

  # Allow our `.envrc`.
  - direnv allow

  # Set `CARGO_HOME` to a cacheable path.
  - export CARGO_HOME="$(git rev-parse --show-toplevel)/.gitlab-ci.d/cargo"

ci:
  stage: ci
  image: nixos/nix:2.18.9
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - direnv exec . cargo run
  cache:
    paths:
      - target
      - .gitlab-ci.d

pages:
  stage: deploy
  image: nixos/nix:2.18.9
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - direnv exec . mdbook build
  artifacts:
    paths:
      - public
