[book]
language = "en"
multilingual = false
src = "doc"
title = "Engage"

[build]
build-dir = "public"

[output.html]
git-repository-icon = "fa-git-square"
git-repository-url = "https://gitlab.computer.surgery/charles/engage"
