[book]
language = "en"
src = "book"
title = "Engage"

[build]
build-dir = "public"

[output.html]
git-repository-icon = "fab-square-git"
git-repository-url = "https://gitlab.computer.surgery/charles/engage"
