[package]
name = "engage"
description = "Yet another task runner"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = [
    "Charles Hall <charles@computer.surgery>",
]

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
crossterm = "0.25.0"
petgraph = "0.6.2"
clap = { version = "3.2.20", features = ["derive"] }
