[workspace]
members = [
    ".",
    "print-readme"
]

[package]
name = "engage"
description = "A task runner with DAG-based parallelism"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://or.computer.surgery/charles/engage"
repository = "https://or.computer.surgery/charles/engage"
readme = "README.md"
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::testing",
]
keywords = [
    "ci",
    "command-line",
    "parallel",
    "runner",
    "task",
]
authors = [
    "Charles Hall <charles@computer.surgery>",
]

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
clap_complete = "4.3.2"
crossterm = "0.26.1"
petgraph = "0.6.3"
serde = { version = "1.0.179", features = ["derive"] }
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"] }
toml = "0.7.6"

[dev-dependencies]
assert_cmd = { version = "2.0.12", features = ["color-auto"] }
insta = "1.31.0"
path_macro = "1.0.0"
predicates = "3.0.3"
strip-ansi-escapes = "0.1.1"
tempfile = "3.7.0"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
