[package]
name = "engage"
description = "A task runner with DAG-based parallelism"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://or.computer.surgery/charles/engage"
repository = "https://or.computer.surgery/charles/engage"
readme = "README.md"
categories = [
    "command-line-utilities",
    "development-tools",
    "development-tools::testing",
]
keywords = [
    "ci",
    "command-line",
    "parallel",
    "runner",
    "task",
]
authors = [
    "Charles Hall <charles@computer.surgery>",
]

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
crossterm = "0.25.0"
petgraph = "0.6.2"
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
toml = "0.5.9"
