[tasks.reuse]
command = ["reuse", "lint"]

[tasks.markdownlint]
command = [
    "bash", "-euo", "pipefail", "-c",

    """
    git ls-files --cached --others --exclude-standard '*.md' \
        | xargs markdownlint
    """
]

[tasks.cargo-fmt]
command = ["cargo", "fmt", "--check", "--", "--color", "always"]

[tasks.graph]
command = [
    "bash", "-euo", "pipefail", "-c",

    """
    TMPFILE=$(mktemp)
    cargo run --color=always -- -f book/assets/tutorial.toml dot | dot -T svg \
        > $TMPFILE
    diff --color=always -u book/assets/tutorial.svg $TMPFILE
    """
]

[tasks.xtask-rustdoc]
command = ["cargo", "xtask", "rustdoc"]

[tasks.xtask-clippy]
command = ["cargo", "xtask", "clippy"]

[tasks.xtask-test]
command = ["cargo", "xtask", "test"]
