interpreter = ["bash", "-euo", "pipefail", "-c"]

[[task]]
name = "reuse"
group = "lints"
script = "reuse lint"

[[task]]
name = "markdownlint"
group = "lints"
script = """
git ls-files --cached --others --exclude-standard '*.md' | xargs markdownlint
"""

[[task]]
name = "cargo-fmt"
group = "lints"
script = "cargo fmt --check -- --color always"

[[task]]
name = "cargo-doc"
group = "lints"
script = """
command=(
    env
        RUSTDOCFLAGS="-D warnings"
    cargo doc
        --workspace
        --locked
        --no-deps
        --document-private-items
        --color always
)

"${command[@]}"
"""

[[task]]
name = "cargo-clippy"
group = "lints"
script = """
command=(
    cargo clippy
        --workspace
        --locked
        --all-targets
        --color always
        --
        -D warnings
)

"${command[@]}"
"""

[[task]]
name = "graphs"
group = "lints"
script = """
for i in $(seq 0 4); do
    TMPFILE=$(mktemp)
    cargo run --color=always -- -f doc/assets/$i.toml dot | dot -T svg \
        > $TMPFILE
    diff --color=always -u doc/assets/$i.svg $TMPFILE
done
"""

[[task]]
# Assert that the readme is up to date according to the files it's comprised of.
name = "readme"
group = "lints"
script = """
TMPFILE=$(mktemp)
cargo --color=always xtask print-readme > $TMPFILE
diff --color=always -u README.md $TMPFILE
"""

[[task]]
# Assert that the description in `Cargo.toml` is up to date.
name = "Cargo.toml"
group = "lints"
script = """
COUNT=$(
    grep -F "description = \\"$(cat assets/tagline.txt)\\"" Cargo.toml --count \
    || true
)

if [ $COUNT -eq 0 ]; then
    echo description is out of date
    exit 1
else
    echo all good
fi
"""

[[task]]
name = "cargo-test"
group = "tests"
script = """
command=(
    cargo llvm-cov
        --workspace
        --locked
        --all-targets
        --color always
        --
        --color always
)

"${command[@]}"
"""
