shell = ["/usr/bin/env", "sh", "-c"]

[[group]]
name = "linter"
depends = ["versioner"]

[[group]]
name = "tester"
depends = ["versioner", "linter"]

[[task]]
name = "nix"
group = "versioner"
cmd = "nix --version"

[[task]]
name = "direnv"
group = "versioner"
cmd = "direnv --version"

[[task]]
name = "rustc"
group = "versioner"
cmd = "rustc --version"

[[task]]
name = "cargo"
group = "versioner"
cmd = "cargo --version"

[[task]]
name = "cargo fmt"
group = "versioner"
cmd = "cargo fmt --version"
depends = ["cargo"]

[[task]]
name = "rustdoc"
group = "versioner"
cmd = "rustdoc --version"

[[task]]
name = "cargo clippy"
group = "versioner"
cmd = "cargo clippy -- --version"
depends = ["cargo"]

[[task]]
name = "nixpkgs-fmt"
group = "versioner"
cmd = "nixpkgs-fmt --version 2> /dev/null"
# This always exits 1 for some reason
ignore = [ 1 ]

[[task]]
name = "markdownlint"
group = "versioner"
cmd = "markdownlint --version"

[[task]]
name = "markdownlint"
group = "linter"
cmd = "markdownlint -i target ."

[[task]]
name = "nixpkgs-fmt"
group = "linter"
cmd = "nixpkgs-fmt --check ."

[[task]]
name = "rustfmt"
group = "linter"
cmd = "cargo fmt -- --color=always --check"

[[task]]
name = "clippy"
group = "linter"
cmd = "cargo clippy --color=always -- -D warnings"

[[task]]
name = "cargo test"
group = "tester"
cmd = "cargo test --color=always --workspace"
