interpreter = ["bash", "-euo", "pipefail", "-c"]

[[task]]
name = "cargo"
group = "versions"
script = "cargo --version"

[[task]]
name = "cargo-fmt"
group = "versions"
script = "cargo fmt --version"
depends = ["cargo"]

[[task]]
name = "cargo-clippy"
group = "versions"
script = "cargo clippy --version"
depends = ["cargo"]

[[task]]
name = "rustc"
group = "versions"
script = "rustc --version"
depends = ["cargo-fmt", "cargo-clippy"]

[[task]]
name = "wait"
group = "database"
# Pretend this is a command that exists
script = "wait-for-database-to-be-ready"

[[task]]
name = "migrate"
group = "database"
# Pretend this is a command that exists too
script = "run-database-migrations"
depends = ["wait"]

[[task]]
name = "cargo"
group = "tests"
script = "cargo test"
