#![doc = env!("CARGO_PKG_DESCRIPTION")]

use std::{
    env,
    io::{Write as _, stderr, stdout},
    iter,
    process::ExitCode,
    sync::{Arc, OnceLock},
};

use clap::error::ErrorKind;
use crossterm::{
    execute,
    style::{Print, Stylize as _},
};
use petgraph::dot::Dot;
use tokio_util::{sync::CancellationToken, task::AbortOnDropHandle};

mod cli;
mod config;
mod error;
mod graph;
mod name;
mod observability;
mod run;

mod exit_code {
    //! Exit codes the program may terminate with.

    /// Success.
    ///
    /// This is used instead of [`ExitCode::SUCCESS`][0] because that's subject
    /// to change based on the platform and we don't want our error exit codes
    /// to overlap with it.
    ///
    /// [0]: std::process::ExitCode::SUCCESS
    pub(crate) const SUCCESS: u8 = 0;

    /// A task failed to run or exited with an uningored non-zero exit code.
    pub(crate) const TASK_ERROR: u8 = 1;

    /// The error was generated by Engage itself.
    pub(crate) const INTERNAL_ERROR: u8 = 2;
}

use name::Name;
use observability::prelude as o;

#[tokio::main]
async fn main() -> ExitCode {
    let Err(e) = try_main().await else {
        return ExitCode::from(exit_code::SUCCESS);
    };

    // Clap prints a good error message when it's the source of the error.
    if !matches!(e, error::Main::Cli) {
        if !matches!(e, error::Main::RunGraph(_)) {
            execute!(
                stderr(),
                Print("Errors".red().bold()),
                Print(":".bold()),
                Print("\n\n"),
            )
            .expect("should be able to write to stderr");
        }

        execute!(
            stderr(),
            Print(error::report::report(iter::once(&e))),
            Print("\n"),
        )
        .expect("should be able to write to stderr");
    }

    match e {
        error::Main::RunGraph(_) => ExitCode::from(exit_code::TASK_ERROR),
        _ => ExitCode::from(exit_code::INTERNAL_ERROR),
    }
}

/// Fallible version of [`main`].
async fn try_main() -> Result<(), error::Main> {
    use error::Main as E;

    let ct = CancellationToken::new();

    let _ct_task = AbortOnDropHandle::new(tokio::task::spawn({
        let ct = ct.clone();
        async move {
            tokio::signal::ctrl_c()
                .await
                .expect("should be able to receive ctrl+c signals");
            o::warn!("cancellation requested");
            ct.cancel();
        }
    }));

    let args = match cli::try_parse() {
        Ok(x) => x,
        Err(e) => {
            e.print().expect("should be able to print message");

            if matches!(
                e.kind(),
                ErrorKind::DisplayHelp | ErrorKind::DisplayVersion
            ) {
                return Ok(());
            }

            return Err(E::Cli);
        }
    };

    let longest_name = Arc::new(OnceLock::new());
    observability::init(longest_name.clone(), args.log_format)
        .map_err(E::Observability)?;

    match &args.subcmd {
        None => run(&args, longest_name, ct, None).await,

        Some(cli::Subcommand::Just {
            task,
        }) => run(&args, longest_name, ct, Some(task)).await,

        Some(cli::Subcommand::Dot {
            task,
        }) => dot(&args, task.as_deref()).await,

        Some(cli::Subcommand::List) => list(args).await,

        Some(cli::Subcommand::Completions {
            shell,
        }) => {
            clap_complete::generate(
                *shell,
                &mut cli::command(),
                env!("CARGO_PKG_NAME"),
                &mut stdout(),
            );

            Ok(())
        }
    }
}

/// Run a graph, or the subgraph targeting `task` specifically.
async fn run(
    args: &cli::Args,
    longest_name: Arc<OnceLock<usize>>,
    ct: CancellationToken,
    task: Option<&Name>,
) -> Result<(), error::Main> {
    use error::Main as E;

    let config =
        config::load(args.file.as_ref()).await.map_err(E::LoadConfig)?;
    longest_name
        .set(
            config
                .tasks
                .keys()
                .map(|x| AsRef::<str>::as_ref(x).len())
                .max()
                .unwrap_or(0),
        )
        .expect("value should not be set yet");

    let g = graph::build(&config.tasks).map_err(E::BuildGraph)?;

    let g = if let Some(task) = task {
        graph::subgraph_targeting(&g, task).map_err(E::TaskNotFound)?
    } else {
        g
    };

    graph::ensure_acyclic(&g).map_err(E::Cyclic)?;

    run::run_graph(Arc::new(g), args.jobs, ct).await.map_err(E::RunGraph)
}

/// Show the Graphviz' `dot` representation of the selection of the graph.
async fn dot(args: &cli::Args, task: Option<&Name>) -> Result<(), error::Main> {
    use error::Main as E;

    let config =
        config::load(args.file.as_ref()).await.map_err(E::LoadConfig)?;
    let graph = graph::build(&config.tasks).map_err(E::BuildGraph)?;

    let graph = match task {
        None => graph,
        Some(task) => {
            graph::subgraph_targeting(&graph, task).map_err(E::TaskNotFound)?
        }
    };

    print!("{}", Dot::new(&graph));

    // Just in case.
    stdout().lock().flush().map_err(|e| E::Stdout(e.into()))?;

    Ok(())
}

/// List available tasks.
async fn list(args: cli::Args) -> Result<(), error::Main> {
    use error::Main as E;

    let config =
        config::load(args.file.as_ref()).await.map_err(E::LoadConfig)?;

    for name in config.tasks.keys() {
        println!("{name}");
    }

    Ok(())
}
