#![doc = env!("CARGO_PKG_DESCRIPTION")]

use std::{
    collections::BTreeSet,
    env,
    io::{stderr, stdout},
    iter,
    path::Path,
    process::ExitCode,
    sync::{Arc, OnceLock},
};

use clap::error::ErrorKind;
use crossterm::{
    execute,
    style::{Print, Stylize as _},
};
use petgraph::dot::Dot;
use tokio::sync::Notify;
use tokio_util::task::AbortOnDropHandle;

mod cli;
mod config;
mod error;
mod graph;
mod name;
mod observability;
mod run;

mod exit_code {
    //! Exit codes the program uses.

    /// Success.
    ///
    /// This is used instead of [`ExitCode::SUCCESS`][0] because that's subject
    /// to change based on the platform and we don't want our error exit codes
    /// to overlap with it.
    ///
    /// [0]: std::process::ExitCode::SUCCESS
    pub(crate) const SUCCESS: u8 = 0;

    /// A process failed to run.
    pub(crate) const PROCESS_ERROR: u8 = 1;

    /// The error was generated by Engage itself.
    pub(crate) const INTERNAL_ERROR: u8 = 2;
}

use name::Name;
use observability::prelude as o;

#[tokio::main]
async fn main() -> ExitCode {
    let Err(e) = try_main().await else {
        return ExitCode::from(exit_code::SUCCESS);
    };

    // Clap prints a good error message when it's the source of the error.
    if !matches!(e, error::Main::Cli) {
        execute!(
            stderr(),
            Print(error::report::report(
                iter::once(&e),
                error::report::Kind::Errors
            )),
            Print("\n"),
        )
        .expect("should be able to write to stderr");
    }

    match e {
        error::Main::RunGraph(_) => ExitCode::from(exit_code::PROCESS_ERROR),
        _ => ExitCode::from(exit_code::INTERNAL_ERROR),
    }
}

/// Fallible version of [`main`].
async fn try_main() -> Result<(), error::Main> {
    use error::Main as E;

    let cancelled = Arc::new(Notify::new());

    let _ctrl_c_handle = AbortOnDropHandle::new(tokio::spawn({
        let cancelled = cancelled.clone();
        async move {
            loop {
                tokio::signal::ctrl_c()
                    .await
                    .expect("should be able to receive ctrl+c signals");
                o::warn!("cancellation requested");
                cancelled.notify_waiters();
            }
        }
    }));

    let args = match cli::try_parse() {
        Ok(x) => x,
        Err(e) => {
            e.print().expect("should be able to print message");

            if matches!(
                e.kind(),
                ErrorKind::DisplayHelp | ErrorKind::DisplayVersion
            ) {
                return Ok(());
            }

            return Err(E::Cli);
        }
    };

    let longest_name = Arc::new(OnceLock::new());

    observability::init(longest_name.clone(), args.log_format())
        .map_err(E::Observability)?;

    match args {
        cli::Args::Run {
            file,
            processes,
            ..
        } => run(cancelled, longest_name, file.as_deref(), processes).await,

        cli::Args::Dot {
            file,
            processes,
            relaxed,
        } => dot(file.as_deref(), processes, relaxed).await,

        cli::Args::List {
            all,
            file,
            relaxed,
        } => list(all, file.as_deref(), relaxed).await,

        cli::Args::Completions {
            shell,
        } => {
            clap_complete::generate(
                shell,
                &mut cli::command(),
                env!("CARGO_PKG_NAME"),
                &mut stdout(),
            );

            Ok(())
        }
    }
}

/// Run a graph, or a subgraph created from the selected `processes`.
async fn run(
    cancelled: Arc<Notify>,
    longest_name: Arc<OnceLock<usize>>,
    file: Option<&Path>,
    processes: Vec<Box<Name>>,
) -> Result<(), error::Main> {
    use error::Main as E;

    let processes = dedup_processes(processes).map_err(E::ProcessesRepeated)?;

    let (config, root_dir) = config::load(file).await.map_err(E::LoadConfig)?;

    longest_name
        .set(
            config
                .processes
                .keys()
                .map(|x| AsRef::<str>::as_ref(x).len())
                .max()
                .unwrap_or(0),
        )
        .expect("value should not be set yet");

    let (graph, errors) = graph::build(&config.processes);

    if !errors.is_empty() {
        return Err(E::BuildGraph(errors));
    }

    let graph = if processes.is_empty() {
        graph
    } else {
        graph::subgraph(&graph, &processes).map_err(E::ProcessesNotFound)?
    };

    run::run_graph(cancelled, Arc::new(graph), root_dir.into())
        .await
        .map_err(E::RunGraph)
}

/// Print a graph in Graphviz' DOT language of processes and their dependencies.
async fn dot(
    file: Option<&Path>,
    processes: Vec<Box<Name>>,
    relaxed: bool,
) -> Result<(), error::Main> {
    use error::Main as E;

    let processes = dedup_processes(processes).map_err(E::ProcessesRepeated)?;

    let (config, _) = config::load(file).await.map_err(E::LoadConfig)?;
    let (graph, errors) = graph::build(&config.processes);

    if !errors.is_empty() && !relaxed {
        execute!(
            stderr(),
            Print("Note".cyan().bold()),
            Print(": "),
            Print(
                "the `-r`/`--relaxed` option can be used to treat the \
                 following errors as warnings"
            ),
            Print("\n\n"),
        )
        .expect("should be able to write to stderr");

        return Err(E::BuildGraph(errors));
    }

    let graph = if processes.is_empty() {
        graph
    } else {
        graph::subgraph(&graph, &processes).map_err(E::ProcessesNotFound)?
    };

    // Print the graph.
    execute!(stdout(), Print(Dot::new(&graph)))
        .expect("should be able to write to stdout");

    if !errors.is_empty() {
        // Print the errors as warnings.
        execute!(
            stderr(),
            Print(error::report::report(
                &errors,
                error::report::Kind::Warnings
            )),
            Print("\n")
        )
        .expect("should be able to write to stderr");
    }

    Ok(())
}

/// List processes.
async fn list(
    all: bool,
    file: Option<&Path>,
    relaxed: bool,
) -> Result<(), error::Main> {
    use error::Main as E;

    let (config, _) = config::load(file).await.map_err(E::LoadConfig)?;

    let (_, errors) = graph::build(&config.processes);

    if !errors.is_empty() && !relaxed {
        execute!(
            stderr(),
            Print("Note".cyan().bold()),
            Print(": "),
            Print(
                "the `-r`/`--relaxed` option can be used to treat the \
                 following errors as warnings"
            ),
            Print("\n\n"),
        )
        .expect("should be able to write to stderr");

        return Err(E::BuildGraph(errors));
    }

    for name in config
        .processes
        .iter()
        .filter_map(|(k, v)| (all || v.part_of.is_none()).then_some(&**k))
    {
        println!("{name}");
    }

    if !errors.is_empty() {
        // Print the errors as warnings.
        execute!(
            stderr(),
            Print(error::report::report(
                &errors,
                error::report::Kind::Warnings
            )),
            Print("\n")
        )
        .expect("should be able to write to stderr");
    }

    Ok(())
}

/// Deduplicate a list of processes into a set.
fn dedup_processes(
    xs: Vec<Box<Name>>,
) -> Result<BTreeSet<Box<Name>>, BTreeSet<error::ProcessRepeated>> {
    use error::ProcessRepeated as E;

    let mut oks = BTreeSet::new();
    let mut errs = BTreeSet::new();

    for x in xs {
        if oks.contains(&x) {
            errs.insert(E(x));
        } else {
            oks.insert(x);
        }
    }

    if !errs.is_empty() {
        return Err(errs);
    }

    Ok(oks)
}
