[package]
name = "xtask"
description = "Task automation."
version = "0.0.0-dev"
publish = false
edition = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
cargo_metadata = { workspace = true }
clap = { workspace = true, features = ["derive"] }
derail = { workspace = true }
derail-macros = { workspace = true }
derail-report = { workspace = true }
itertools = { workspace = true }
