#!/usr/bin/env bash
set -e

# Generates enhanced shell completions with dynamic process discovery
# and improved visual organization (grouping flags and moving them to the end).

# Ensure we're in the project root
if [ ! -f "Cargo.toml" ]; then
    echo "Error: Must be run from project root" >&2
    exit 1
fi

echo "Generating shell completions..."

mkdir -p completions/share/bash-completion/completions
mkdir -p completions/share/zsh/site-functions
mkdir -p completions/share/fish/vendor_completions.d

# --- Bash ---
cargo run -q -- completions bash > completions/share/bash-completion/completions/engage

# Dynamic process list for -p and --process
sed -i '/--process)/,+2 s|COMPREPLY=($(compgen -f "${cur}"))|COMPREPLY=($(compgen -W "$(engage list --relaxed 2>/dev/null)" -- "${cur}"))|' completions/share/bash-completion/completions/engage
sed -i '/-p)/,+2 s|COMPREPLY=($(compgen -f "${cur}"))|COMPREPLY=($(compgen -W "$(engage list --relaxed 2>/dev/null)" -- "${cur}"))|' completions/share/bash-completion/completions/engage

# Reorder opts: move commands to front, group short/long flags
# We target the main command opts specifically
sed -i 's|opts="-f -l -p -h -V --file --log-format --process --help --version completions dot list help"|opts="completions dot list help -f --file -l --log-format -p --process -V --version -h --help"|' completions/share/bash-completion/completions/engage
sed -i 's|opts="-f -p -r -h --file --process --relaxed --help"|opts="-r --relaxed -f --file -p --process -h --help"|' completions/share/bash-completion/completions/engage
sed -i 's|opts="-f -r -h --file --relaxed --help"|opts="-r --relaxed -f --file -h --help"|' completions/share/bash-completion/completions/engage


# --- Zsh ---
cargo run -q -- completions zsh > completions/share/zsh/site-functions/_engage

# Dynamic process list for -p and --process
sed -i 's|:PROCESS:_default|:PROCESS:($(engage list --relaxed 2>/dev/null))|' completions/share/zsh/site-functions/_engage

# Group flags (-f | --file, etc.)
# This regex merges the short and long entries generated by clap_complete into a single Zsh grouped entry.
sed -i "s|'-f+\[\(.*\)\]:FILE:_files'|'(-f --file)-f+[\1]:FILE:_files'|g" completions/share/zsh/site-functions/_engage
sed -i "s|'--file=\[\(.*\)\]:FILE:_files'|'(--file -f)--file=[\1]:FILE:_files'|g" completions/share/zsh/site-functions/_engage

sed -i "s|'\*-p+\[\(.*\)\]:PROCESS:\(.*\)'|'(-p --process)*-p+[\1]:PROCESS:\2'|g" completions/share/zsh/site-functions/_engage
sed -i "s|'\*--process=\[\(.*\)\]:PROCESS:\(.*\)'|'(--process -p)*--process=[\1]:PROCESS:\2'|g" completions/share/zsh/site-functions/_engage

sed -i "s|'-l+\[\(.*\)\]:FORMAT:\(.*\)'|'(-l --log-format)-l+[\1]:FORMAT:\2'|g" completions/share/zsh/site-functions/_engage
sed -i "s|'--log-format=\[\(.*\)\]:FORMAT:\(.*\)'|'(--log-format -l)--log-format=[\1]:FORMAT:\2'|g" completions/share/zsh/site-functions/_engage


# --- Fish ---
cargo run -q -- completions fish > completions/share/fish/vendor_completions.d/engage.fish

# Dynamic process list for -p and --process
sed -i 's|-s p -l process -d '\''Select a process'\'' -r|-s p -l process -d '\''Select a process'\'' -f -a "(engage list --relaxed 2>/dev/null)"|' completions/share/fish/vendor_completions.d/engage.fish

echo "Completions generated in completions/"
