//! # `engage`
#![doc = "\n"]
#![doc = include_str!("../assets/tagline.txt")]

use std::{
    env,
    io::{stdout, Write},
    process::ExitCode,
};

use crossterm::style::Stylize;
use petgraph::dot::Dot;

mod args;
mod error;
mod file;
mod graph;
mod ui;

mod exit_code {
    //! Exit codes the program may terminate with

    /// Success
    ///
    /// This is used instead of [`ExitCode::SUCCESS`][0] because that's subject
    /// to change based on the platform and we don't want our error exit codes
    /// to overlap with it.
    ///
    /// [0]: std::process::ExitCode::SUCCESS
    pub(crate) const SUCCESS: u8 = 0;

    /// A task failed to run or exited with an uningored non-zero exit code
    pub(crate) const TASK_ERROR: u8 = 1;

    /// The error was generated by Engage itself
    pub(crate) const INTERNAL_ERROR: u8 = 2;
}

#[tokio::main]
async fn main() -> ExitCode {
    let Err(e) = try_main().await else {
        return ExitCode::from(exit_code::SUCCESS);
    };

    if let error::Main::RunGraph(error::RunGraph::Task) = &e {
        ExitCode::from(exit_code::TASK_ERROR)
    } else {
        // The error was generated by engage itself
        eprintln!(
            "{}{} {}",
            "error".bold().red(),
            ':'.bold(),
            error::Chain(&e),
        );

        ExitCode::from(exit_code::INTERNAL_ERROR)
    }
}

/// Fallible version of [`main`]
async fn try_main() -> Result<(), error::Main> {
    use error::Main as Error;

    let args = args::parse();

    // Find the Engage file and change the current directory to its directory
    let file = match args.file {
        None => file::find().await.map_err(Error::FileFind)?,
        Some(file) => file.canonicalize().map_err(Error::CanonicalizeGiven)?,
    };
    env::set_current_dir(file.parent().ok_or(Error::NoParentDirectory)?)
        .map_err(Error::ChangeDirectory)?;

    let contents = std::fs::read_to_string(file).map_err(Error::ReadFile)?;

    let mut file: file::File = toml::from_str(&contents)?;

    file.normalize();
    file.validate()?;

    match args.subcmd {
        // Run everything
        None => {
            let graph = graph::from_file(&file)?;
            ui::run_graph(graph, file, args.jobs).await.map_err(Into::into)
        }

        // Run a subgraph
        Some(args::Subcommand::Just(args::Just {
            group,
            task,
        })) => {
            let graph = graph::subgraph_targeting(
                &graph::from_file(&file).map_err(Error::Graph)?,
                group,
                task,
            )
            .map_err(Error::NotFound)?;

            ui::run_graph(graph, file, args.jobs).await.map_err(Into::into)
        }

        // Show the Graphviz' `dot` representation of the selection of the graph
        Some(args::Subcommand::Dot {
            group,
            task,
        }) => {
            let graph = graph::from_file(&file)?;

            let graph = match group {
                None => graph,
                Some(group) => graph::subgraph_targeting(&graph, group, task)?,
            };

            print!("{}", Dot::new(&graph));

            // Just in case
            stdout().lock().flush().map_err(Error::Stdout)?;

            Ok(())
        }

        // List available groups and tasks
        Some(args::Subcommand::List) => {
            // Unstable is fine because duplicate names are not allowed
            file.groups.sort_unstable_by(|a, b| a.name.cmp(&b.name));
            file.tasks.sort_unstable_by(|a, b| a.name.cmp(&b.name));

            for (i, group) in file.groups.iter().enumerate() {
                println!("{}:", group.name);

                let tasks = file.tasks.iter().filter(|x| x.group == group.name);

                for task in tasks {
                    println!("    {}", task.name);
                }

                if i + 1 < file.groups.len() {
                    println!();
                }
            }

            Ok(())
        }

        Some(args::Subcommand::Completions {
            shell,
        }) => {
            clap_complete::generate(
                shell,
                &mut args::command(),
                env!("CARGO_PKG_NAME"),
                &mut stdout(),
            );

            Ok(())
        }
    }
}
