#![doc = env!("CARGO_PKG_DESCRIPTION")]

use std::{
    env,
    io::{Write as _, stdout},
    iter,
    process::ExitCode,
};

use clap::error::ErrorKind;
use petgraph::dot::Dot;

mod cli;
mod config;
mod error;
mod graph;
mod process;
mod ui;

mod exit_code {
    //! Exit codes the program may terminate with.

    /// Success.
    ///
    /// This is used instead of [`ExitCode::SUCCESS`][0] because that's subject
    /// to change based on the platform and we don't want our error exit codes
    /// to overlap with it.
    ///
    /// [0]: std::process::ExitCode::SUCCESS
    pub(crate) const SUCCESS: u8 = 0;

    /// A task failed to run or exited with an uningored non-zero exit code.
    pub(crate) const TASK_ERROR: u8 = 1;

    /// The error was generated by Engage itself.
    pub(crate) const INTERNAL_ERROR: u8 = 2;
}

#[tokio::main]
async fn main() -> ExitCode {
    let Err(e) = try_main().await else {
        return ExitCode::from(exit_code::SUCCESS);
    };

    // Clap prints a good error message when it's the source of the error.
    if !matches!(e, error::Main::Cli) {
        eprintln!(
            "Errors:\n{}",
            derail_report::multiline::<_, _, derail_report::HeapFactory>(
                iter::once(&e)
            ),
        );
    }

    match e {
        error::Main::RunGraph(error::RunGraph::Task(_)) => {
            ExitCode::from(exit_code::TASK_ERROR)
        }
        _ => ExitCode::from(exit_code::INTERNAL_ERROR),
    }
}

/// Fallible version of [`main`].
async fn try_main() -> Result<(), error::Main> {
    use error::Main as E;

    let args = match cli::try_parse() {
        Ok(x) => x,
        Err(e) => {
            e.print().expect("should be able to print message");

            if matches!(
                e.kind(),
                ErrorKind::DisplayHelp | ErrorKind::DisplayVersion
            ) {
                return Ok(());
            }

            return Err(E::Cli);
        }
    };

    match &args.subcmd {
        // Run everything.
        None => {
            let config = config::load(&args).await.map_err(E::LoadConfig)?;
            let graph = graph::build(&config).map_err(E::Graph)?;
            ui::run_graph(graph, config, args.jobs).await.map_err(E::RunGraph)
        }

        // Run a subgraph.
        Some(cli::Subcommand::Just(cli::Just {
            group,
            task,
        })) => {
            let config = config::load(&args).await.map_err(E::LoadConfig)?;
            let graph = graph::subgraph_targeting(
                &graph::build(&config).map_err(E::Graph)?,
                group,
                task.as_ref(),
            )
            .map_err(E::NotFound)?;

            ui::run_graph(graph, config, args.jobs).await.map_err(E::RunGraph)
        }

        // Show the Graphviz' `dot` representation of the selection of the
        // graph.
        Some(cli::Subcommand::Dot {
            group,
            task,
        }) => {
            let config = config::load(&args).await.map_err(E::LoadConfig)?;
            let graph = graph::build(&config).map_err(E::Graph)?;

            let graph = match group {
                None => graph,
                Some(group) => {
                    graph::subgraph_targeting(&graph, group, task.as_ref())
                        .map_err(E::NotFound)?
                }
            };

            print!("{}", Dot::new(&graph));

            // Just in case.
            stdout().lock().flush().map_err(|e| E::Stdout(e.into()))?;

            Ok(())
        }

        // List available groups and tasks.
        Some(cli::Subcommand::List) => {
            let mut config =
                config::load(&args).await.map_err(E::LoadConfig)?;

            // Unstable is fine because duplicate names are not allowed.
            config.groups.sort_unstable_by(|a, b| a.name.cmp(&b.name));
            config.tasks.sort_unstable_by(|a, b| a.name.cmp(&b.name));

            for (i, group) in config.groups.iter().enumerate() {
                println!("{}:", group.name);

                let tasks =
                    config.tasks.iter().filter(|x| x.group == group.name);

                for task in tasks {
                    println!("    {}", task.name);
                }

                if i + 1 < config.groups.len() {
                    println!();
                }
            }

            Ok(())
        }

        Some(cli::Subcommand::Completions {
            shell,
        }) => {
            clap_complete::generate(
                *shell,
                &mut cli::command(),
                env!("CARGO_PKG_NAME"),
                &mut stdout(),
            );

            Ok(())
        }
    }
}
