//! # `engage`
#![doc = "\n"]
#![doc = include_str!("../assets/tagline.txt")]

use std::{
    env,
    io::{stdout, Write as _},
    iter,
    process::ExitCode,
};

use crossterm::style::Stylize as _;
use petgraph::dot::Dot;
use schemars::schema_for;

mod args;
mod error;
mod file;
mod graph;
mod ui;

mod exit_code {
    //! Exit codes the program may terminate with.

    /// Success.
    ///
    /// This is used instead of [`ExitCode::SUCCESS`][0] because that's subject
    /// to change based on the platform and we don't want our error exit codes
    /// to overlap with it.
    ///
    /// [0]: std::process::ExitCode::SUCCESS
    pub(crate) const SUCCESS: u8 = 0;

    /// A task failed to run or exited with an uningored non-zero exit code.
    pub(crate) const TASK_ERROR: u8 = 1;

    /// The error was generated by Engage itself.
    pub(crate) const INTERNAL_ERROR: u8 = 2;
}

#[tokio::main]
async fn main() -> ExitCode {
    let Err(e) = try_main().await else {
        return ExitCode::from(exit_code::SUCCESS);
    };

    eprintln!(
        "{}{}\n{}",
        "Errors".bold().red(),
        ':'.bold(),
        derail_report::multiline::<_, _, derail_report::HeapFactory>(
            iter::once(&e)
        ),
    );

    match e {
        error::Main::RunGraph(error::RunGraph::Task(_)) => {
            ExitCode::from(exit_code::TASK_ERROR)
        }
        _ => ExitCode::from(exit_code::INTERNAL_ERROR),
    }
}

/// Fallible version of [`main`].
async fn try_main() -> Result<(), error::Main> {
    use error::Main as Error;

    let args = args::parse();

    match &args.subcmd {
        // Run everything.
        None => {
            let file = load_file(&args).await?;
            let graph = graph::from_file(&file).map_err(Error::Graph)?;
            ui::run_graph(graph, file, args.jobs).await.map_err(Error::RunGraph)
        }

        // Run a subgraph.
        Some(args::Subcommand::Just(args::Just {
            group,
            task,
        })) => {
            let file = load_file(&args).await?;
            let graph = graph::subgraph_targeting(
                &graph::from_file(&file).map_err(Error::Graph)?,
                group,
                task.as_ref(),
            )
            .map_err(Error::NotFound)?;

            ui::run_graph(graph, file, args.jobs).await.map_err(Error::RunGraph)
        }

        // Show the Graphviz' `dot` representation of the selection of the
        // graph.
        Some(args::Subcommand::Dot {
            group,
            task,
        }) => {
            let file = load_file(&args).await?;
            let graph = graph::from_file(&file).map_err(Error::Graph)?;

            let graph = match group {
                None => graph,
                Some(group) => {
                    graph::subgraph_targeting(&graph, group, task.as_ref())
                        .map_err(Error::NotFound)?
                }
            };

            print!("{}", Dot::new(&graph));

            // Just in case.
            stdout().lock().flush().map_err(|e| Error::Stdout(e.into()))?;

            Ok(())
        }

        // List available groups and tasks.
        Some(args::Subcommand::List) => {
            let mut file = load_file(&args).await?;

            // Unstable is fine because duplicate names are not allowed.
            file.groups.sort_unstable_by(|a, b| a.name.cmp(&b.name));
            file.tasks.sort_unstable_by(|a, b| a.name.cmp(&b.name));

            for (i, group) in file.groups.iter().enumerate() {
                println!("{}:", group.name);

                let tasks = file.tasks.iter().filter(|x| x.group == group.name);

                for task in tasks {
                    println!("    {}", task.name);
                }

                if i + 1 < file.groups.len() {
                    println!();
                }
            }

            Ok(())
        }

        Some(args::Subcommand::Completions {
            shell,
        }) => {
            clap_complete::generate(
                *shell,
                &mut args::command(),
                env!("CARGO_PKG_NAME"),
                &mut stdout(),
            );

            Ok(())
        }

        Some(args::Subcommand::Schema) => {
            let schema = serde_json::to_string_pretty(&schema_for!(file::File))
                .expect("should be able to serialize JSON Schema document");
            println!("{schema}");

            Ok(())
        }
    }
}

/// Attempt to load an Engage file.
async fn load_file(args: &args::Args) -> Result<file::File, error::Main> {
    use error::Main as Error;

    let file = match &args.file {
        None => file::find().await.map_err(|e| Error::FileFind(e.into()))?,
        Some(file) => file
            .canonicalize()
            .map_err(|e| Error::CanonicalizeGiven(e.into()))?,
    };

    env::set_current_dir(file.parent().ok_or(Error::NoParentDirectory)?)
        .map_err(|e| Error::ChangeDirectory(e.into()))?;

    let contents =
        std::fs::read_to_string(file).map_err(|e| Error::ReadFile(e.into()))?;
    let mut file: file::File =
        toml::from_str(&contents).map_err(|e| Error::Deserialize(e.into()))?;

    file.normalize();
    file.validate().map_err(Error::File)?;

    Ok(file)
}
